# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "SimpleNotifyDemo" do

pod 'HTPressableButton'
pod "MaterialDesignCocoa"

end

target "SimpleNotifyDemoTests" do

end

